# Generated by Django 4.0.2 on 2022-02-01 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('designer', models.CharField(max_length=25)),
                ('year_released', models.IntegerField()),
                ('number_of_players', models.IntegerField()),
                ('game_duration', models.IntegerField()),
                ('age_recommendation', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('username', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=100)),
                ('gameId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamerapi.game')),
                ('playerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamerapi.player')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('gameId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamerapi.game')),
                ('playerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamerapi.player')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=25)),
                ('gameId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamerapi.game')),
                ('playerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamerapi.player')),
            ],
        ),
        migrations.CreateModel(
            name='GameCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamerapi.category')),
                ('gameId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamerapi.game')),
            ],
        ),
    ]
