# Generated by Django 4.0.2 on 2022-02-02 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamerapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamecategory',
            old_name='categoryId',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='gamecategory',
            old_name='gameId',
            new_name='game',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='playerId',
            new_name='game',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='gameId',
            new_name='player',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='gameId',
            new_name='game',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='playerId',
            new_name='player',
        ),
        migrations.RenameField(
            model_name='url',
            old_name='gameId',
            new_name='game',
        ),
        migrations.RenameField(
            model_name='url',
            old_name='playerId',
            new_name='player',
        ),
        migrations.AlterField(
            model_name='game',
            name='game_duration',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='game',
            name='year_released',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='url',
            name='image_url',
            field=models.CharField(max_length=300),
        ),
    ]
